name: Build Chxl Launcher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Integrate vcpkg
      run: |
        vcpkg integrate install

    - name: Install Dependencies (vcpkg)
      run: |
        vcpkg install imgui[dx11-binding,win32-binding]:x64-windows nlohmann-json:x64-windows curl:x64-windows

    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -A x64

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChxlLauncher-Release
        path: build/Release/ChxlLauncher.exe
